import { motion, AnimatePresence } from 'framer-motion';
import { FiX } from 'react-icons/fi';
import { RiAiGenerate } from 'react-icons/ri';

const BookSummaryModal = ({ isOpen, onClose, summary, isLoading }) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.9, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.9, y: 20 }}
            className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="bg-indigo-600 text-white p-4 flex justify-between items-center">
              <div className="flex items-center">
                <RiAiGenerate size={24} className="mr-2" />
                <h3 className="font-bold">AI-Generated Book Summary</h3>
              </div>
              <button onClick={onClose} className="text-white hover:text-indigo-200">
                <FiX size={20} />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto flex-1">
              {isLoading ? (
                <div className="flex flex-col items-center justify-center h-40">
                  <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-indigo-600 mb-4"></div>
                  <p className="text-gray-600">Generating AI summary...</p>
                </div>
              ) : (
                <div className="prose">
                  <p className="whitespace-pre-line">{summary}</p>
                  <div className="mt-4 p-3 bg-indigo-50 text-indigo-700 rounded-lg text-sm">
                    <p className="font-medium">Note:</p>
                    <p>This summary is generated by AI based on the book's metadata and may not capture all nuances.</p>
                  </div>
                </div>
              )}
            </div>
            
            <div className="border-t border-gray-200 p-4 flex justify-end">
              <button
                onClick={onClose}
                className="bg-indigo-600 text-white px-6 py-2 rounded-lg hover:bg-indigo-700 transition-colors"
              >
                Close
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default BookSummaryModal;